# -*- coding: utf-8 -*-
# Copyright (c) OpenValue All Rights Reserved

{
  'name': 'MRO Maintenance',
  'summary': 'MRO Maintenance',
  'version': '14.0.2.2',
  'category': 'Manufacturing/Maintenance',
  "website": 'www.openvalue.cloud',
  'author': "OpenValue",
  'support': 'info@openvalue.cloud',
  'license': "Other proprietary",
  'price': 1000.00,
  'currency': 'EUR',
  'depends': [
        'mail',
        'attachment_indexation',
        'resource',
        'contacts',
        'stock_account',
        'analytic',
        'hr',
    ],
   'data': [
        'data/mro_maintenance_sequence.xml',
        'data/stock_location_data.xml',
        'security/mro_maintenance_security.xml',
        'security/ir.model.access.csv',
        'views/stock_account_location_views.xml',
        'views/mro_maintenance_menu_views.xml',
        'views/mro_equipment_category_views.xml',
        'views/mro_equipment_location_views.xml',
        'views/hr_employee_views.xml',
        'views/product_views.xml',
        'views/mail_activity_views.xml',
        'views/mro_maintenance_team_views.xml',
        'views/mro_equipment_views.xml',
        'views/mro_maintenance_plan_views.xml',
        'views/mro_tool_views.xml',
        'views/mro_operations_views.xml',
        'views/mro_task_views.xml',
        'views/mro_gauge_views.xml',
        'views/mro_meter_views.xml',
        'wizards/mro_reject_request_views.xml',
        'wizards/mro_convert_order_task_views.xml',
        'wizards/mro_reject_request_order_views.xml',
        'views/account_analytic_line_views.xml',
        'views/mro_request_views.xml',
        'views/mro_order_views.xml',
        'reports/reports_mro.xml',
        'reports/report_mro_order.xml',
        'reports/report_mro_request.xml',
        'views/mro_dashboard_views.xml',
        'wizards/mro_on_condition_planning_views.xml',
        'wizards/mro_periodic_planning_views.xml',
        'wizards/mro_maintenance_plan_run_views.xml',
        'wizards/tool_utilization.xml',
    ],
  'application': True,
  'installable': True,
  'auto_install': False,
  'images': ['static/description/banner.png'],
}
